### ISSUE TITLE
Как перейти с MVC?

### ISSUE THREAD

**Issue by kompolom** [bem-contrib/bem-redux#3]
Только начал знакомиться с redux - мозг взрывает, если честно после MVC.

Имею несколько вопросов:
- как на изменение state рендерить только изменившиеся?
- как создавать middleware?
- как обеспечить целостность схемы данных (раньше этим модель занималась)?
- как _лучше_ передавать начальное состояние?
- как портировать коллекции из MVC?

**Comment by rakchaev** [comment]
Привет!

Подробнее и с примерами про redux лучше почитать/посмотреть:
- http://redux.js.org
- https://github.com/rajdee/redux-in-russian
- https://egghead.io/series/getting-started-with-redux

Это просто обвязка над Redux, чтобы использовать в БЭМ-проектах.
