### ISSUE TITLE
Arrow functions in block redux-state-container

### ISSUE THREAD

**Issue by adinvadim** [bem-contrib/bem-redux#5]
https://github.com/bem-contrib/bem-redux/blob/master/common.blocks/redux-state-container/redux-state-container.js#L18

Often projects on BEM not use Babel

**Comment by adinvadim** [comment]
I can send a PR

**Comment by rakchaev** [comment]
Okay. Let's do it.
It's only one code line with es2015, isn't it?

**Comment by adinvadim** [comment]
Yes.
https://github.com/bem-contrib/bem-redux/pull/6

**Comment by rakchaev** [comment]
Closed in favor of https://github.com/bem-contrib/bem-redux/pull/6.
